p8105\_hw1\_xz2981
================
Xinyan Zhou
2021/9/25

``` r
library(tidyverse)
```

    ## -- Attaching packages --------------------------------------- tidyverse 1.3.1 --

    ## v ggplot2 3.3.5     v purrr   0.3.4
    ## v tibble  3.1.4     v dplyr   1.0.7
    ## v tidyr   1.1.3     v stringr 1.4.0
    ## v readr   2.0.1     v forcats 0.5.1

    ## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(palmerpenguins)
```

# Problem 1

## Create the dataframe

``` r
data_p1 <- tibble(
  norm_samp = rnorm(10,0,1),
  var_logic = norm_samp > 0,
  var_char = "maple glazed donuts",
  var_factor = factor(c("low","low","medium","medium","high","high",
                         "high","high","high","high"))
)
print(data_p1)
```

    ## # A tibble: 10 x 4
    ##    norm_samp var_logic var_char            var_factor
    ##        <dbl> <lgl>     <chr>               <fct>     
    ##  1   1.71    TRUE      maple glazed donuts low       
    ##  2   3.36    TRUE      maple glazed donuts low       
    ##  3   0.638   TRUE      maple glazed donuts medium    
    ##  4  -0.00127 FALSE     maple glazed donuts medium    
    ##  5  -1.27    FALSE     maple glazed donuts high      
    ##  6  -1.57    FALSE     maple glazed donuts high      
    ##  7  -1.16    FALSE     maple glazed donuts high      
    ##  8  -0.650   FALSE     maple glazed donuts high      
    ##  9   0.383   TRUE      maple glazed donuts high      
    ## 10  -0.249   FALSE     maple glazed donuts high

## Take the mean

The following variables can work:

``` r
mean(pull(data_p1,norm_samp))
```

    ## [1] 0.1188024

``` r
mean(pull(data_p1,var_logic))
```

    ## [1] 0.4

The following variables cannot work:

``` r
# mean(pull(data_p1,var_char))
# mean(pull(data_p1,var_factor))
```

When we explicitly convert variables from one type to another, we can
take the mean for the following two variables:

``` r
mean(as.numeric(pull(data_p1,var_logic)))
mean(as.numeric(pull(data_p1,var_factor)))
```

Even after converting, we cannot take the mean for var\_char.

``` r
# mean(as.numeric(pull(data_p1,var_char)))
```

# Problem 2

## Load the dataset

``` r
data("penguins", package = "palmerpenguins")
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

``` r
mean(pull(penguins,flipper_length_mm),na.rm = TRUE)
```

    ## [1] 200.9152

This dataset has 8 variables: species, factor, three
levels-“Adelie”,“Chinstrap”,“Gentoo”; island, factor, three
levels-“Biscoe”,“Dream”, “Torgersen”; bill\_length\_mm, numeric, from
32.10 to 59.60, with 2 missing values; bill\_depth\_mm, numeric, from
13.10 to 21.50, with 2 missing values; flipper\_length\_mm, integer,
from 172 to 231, with 2 missing values; body\_mass\_g, integer, from
2700 to 6300, with 2 missing values; sex, factor, 2
levels-“female”,“male”,with 11 missing values; year, integer, from 2007
to 2009.

The row of the data is 344, and the column is 8.

The mean of flipper length is 200.9152.

## Scatterplot

``` r
penguins %>%
  ggplot(aes(flipper_length_mm,bill_length_mm)) + 
  geom_point(alpha = 0.5, size = 2, aes(color = species)) 
```

![](p8105_hw1_xz2981_files/figure-gfm/unnamed-chunk-8-1.png)<!-- -->

``` r
ggsave("penguins.pdf")
```
